"""ORM models package — import order matters for Alembic autogenerate."""

from app.models.platform_user import PlatformUser
from app.models.platform_session import PlatformSession
from app.models.platform_owner import PlatformOwner
from app.models.owner_session import OwnerSession
from app.models.tenant import Tenant
from app.models.user import User
from app.models.role import Role, Permission, RoleAssignment
from app.models.session import UserSession
from app.models.service_request import ServiceRequest
from app.models.support_ticket import SupportTicket, SupportTicketMessage
from app.models.catalog import Plan, Module
from app.models.billing import (
    Coupon,
    Order,
    OutboxEmail,
    PlatformInvoice,
    PlatformInvoiceLine,
    PlatformPayment,
    Subscription,
    TenantModule,
    TenantSetting,
)
from app.models.audit import AuditLog
from app.models.platform_setting import (
    PLATFORM_SETTING_DEFAULTS,
    PLATFORM_SETTING_INT_KEYS,
    PlatformSetting,
)
from app.models.academic import AcademicYear, Department, SchoolClass, Subject, ClassGrade, ClassProgram
from app.models.enrollment import Enrollment, TeacherSubject
from app.models.principal import (
    AttendanceSession,
    AttemptStatus,
    Exam,
    ExamAttempt,
    ExamHallAllocation,
    ExamStatus,
    MalpracticeLog,
    Notice,
    NoticeRead,
    ResultOutcome,
    ResultPublication,
    StaffLeaveRequest,
    StaffProfile,
    StudentResult,
    TimetableSlot,
)
from app.models.hod import (
    Assignment,
    AttendanceRecord,
    DiscussionThread,
    MentorAssignment,
    Submission,
)
from app.models.library import Book, BookCondition, BookCopy, BookIssue, EResource
from app.models.coordinator import (
    AcademicEvent,
    AcademicEventScope,
    AcademicEventType,
    TimetableSubstitution,
)
from app.models.exam_controller import (
    ExamControllerGradeCard,
    ExamControllerGradeCardStatus,
    ExamControllerPublication,
    ExamControllerPublicationStatus,
)
from app.models.lms import (
    Answer,
    AttendanceLeave,
    ContentAccessLog,
    ContentItem,
    ContentKind,
    ContentTag,
    DifficultyLevel,
    DiscussionReply,
    DiscussionVote,
    ExamSection,
    FeeAccountStatus,
    FeeInstallment,
    FeePayment,
    FeeStructure,
    InstallmentStatus,
    LeaveStatus,
    Milestone,
    PaymentMode,
    ProjectGroup,
    ProjectGroupInvitation,
    ProjectGroupMember,
    ProjectGroupMessage,
    ProjectGroupResource,
    ProjectGroupTask,
    Question,
    QuestionBankItem,
    QuestionOption,
    QuestionType,
    ReviewDecision,
    Scholarship,
    ScholarshipGrant,
    StudentFeeAccount,
    SubmissionFile,
    SubmissionReview,
)

__all__ = [
    "PlatformUser",
    "PlatformSession",
    "PlatformOwner",
    "OwnerSession",
    "Tenant",
    "User",
    "Role",
    "Permission",
    "RoleAssignment",
    "UserSession",
    "ServiceRequest",
    "SupportTicket",
    "SupportTicketMessage",
    "Plan",
    "Module",
    "Subscription",
    "TenantModule",
    "TenantSetting",
    "PlatformInvoice",
    "PlatformInvoiceLine",
    "PlatformPayment",
    "Coupon",
    "Order",
    "OutboxEmail",
    "AuditLog",
    "PlatformSetting",
    "PLATFORM_SETTING_DEFAULTS",
    "PLATFORM_SETTING_INT_KEYS",
    "AcademicYear",
    "Department",
    "SchoolClass",
    "Subject",
    "ClassGrade",
    "ClassProgram",
    "AttendanceSession",
    "AttemptStatus",
    "Exam",
    "ExamAttempt",
    "ExamHallAllocation",
    "ExamStatus",
    "MalpracticeLog",
    "Notice",
    "NoticeRead",
    "ResultOutcome",
    "ResultPublication",
    "StaffLeaveRequest",
    "StaffProfile",
    "StudentResult",
    "TimetableSlot",
    "Assignment",
    "AttendanceRecord",
    "DiscussionThread",
    "MentorAssignment",
    "Submission",
    "AcademicEvent",
    "AcademicEventScope",
    "AcademicEventType",
    "TimetableSubstitution",
    "ExamControllerPublication",
    "ExamControllerPublicationStatus",
    "ExamControllerGradeCard",
    "ExamControllerGradeCardStatus",
    "Answer",
    "AttendanceLeave",
    "ContentAccessLog",
    "ContentItem",
    "ContentKind",
    "ContentTag",
    "DifficultyLevel",
    "DiscussionReply",
    "DiscussionVote",
    "ExamSection",
    "FeeAccountStatus",
    "FeeInstallment",
    "FeeStructure",
    "FeePayment",
    "InstallmentStatus",
    "LeaveStatus",
    "Milestone",
    "PaymentMode",
    "ProjectGroup",
    "ProjectGroupInvitation",
    "ProjectGroupMember",
    "ProjectGroupMessage",
    "ProjectGroupResource",
    "ProjectGroupTask",
    "Question",
    "QuestionBankItem",
    "QuestionOption",
    "QuestionType",
    "ReviewDecision",
    "Scholarship",
    "ScholarshipGrant",
    "StudentFeeAccount",
    "Book",
    "BookCondition",
    "BookCopy",
    "BookIssue",
    "EResource",
    "SubmissionFile",
    "SubmissionReview",
]
