-- Production migration: hostel-safe roll-call, occupancy and tenant integrity.
BEGIN;
ALTER TABLE hostel_blocks DROP CONSTRAINT hostel_blocks_tenant_id_fkey, ADD CONSTRAINT hostel_blocks_tenant_id_fkey FOREIGN KEY(tenant_id) REFERENCES tenants(id) ON DELETE CASCADE;
ALTER TABLE hostel_rooms DROP CONSTRAINT hostel_rooms_tenant_id_fkey, ADD CONSTRAINT hostel_rooms_tenant_id_fkey FOREIGN KEY(tenant_id) REFERENCES tenants(id) ON DELETE CASCADE;
ALTER TABLE hostel_rooms DROP CONSTRAINT hostel_rooms_block_id_fkey, ADD CONSTRAINT hostel_rooms_block_id_fkey FOREIGN KEY(block_id) REFERENCES hostel_blocks(id) ON DELETE CASCADE;
ALTER TABLE hostel_allotments DROP CONSTRAINT hostel_allotments_tenant_id_fkey, ADD CONSTRAINT hostel_allotments_tenant_id_fkey FOREIGN KEY(tenant_id) REFERENCES tenants(id) ON DELETE CASCADE;
ALTER TABLE hostel_attendance DROP CONSTRAINT hostel_attendance_tenant_id_fkey, ADD CONSTRAINT hostel_attendance_tenant_id_fkey FOREIGN KEY(tenant_id) REFERENCES tenants(id) ON DELETE CASCADE;
ALTER TABLE hostel_leave_requests DROP CONSTRAINT hostel_leave_requests_tenant_id_fkey, ADD CONSTRAINT hostel_leave_requests_tenant_id_fkey FOREIGN KEY(tenant_id) REFERENCES tenants(id) ON DELETE CASCADE;
ALTER TABLE hostel_complaints DROP CONSTRAINT hostel_complaints_tenant_id_fkey, ADD CONSTRAINT hostel_complaints_tenant_id_fkey FOREIGN KEY(tenant_id) REFERENCES tenants(id) ON DELETE CASCADE;
DO $$ BEGIN CREATE TYPE hostel_attendance_status AS ENUM ('PRESENT','ABSENT','ON_LEAVE'); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
ALTER TABLE hostel_attendance ALTER COLUMN status DROP DEFAULT;
ALTER TABLE hostel_attendance ALTER COLUMN status TYPE hostel_attendance_status USING (CASE status::text WHEN 'EXCUSED' THEN 'ON_LEAVE' WHEN 'LATE' THEN 'PRESENT' ELSE status::text END)::hostel_attendance_status;
ALTER TABLE hostel_blocks ADD CONSTRAINT uq_hostel_blocks_tenant_name UNIQUE (tenant_id,name);
ALTER TABLE hostel_rooms ADD CONSTRAINT ck_hostel_rooms_capacity CHECK (capacity > 0 AND monthly_fee >= 0 AND floor >= 0);
ALTER TABLE hostel_allotments ALTER COLUMN bed_number SET NOT NULL;
ALTER TABLE hostel_allotments ADD CONSTRAINT ck_hostel_allotment_dates CHECK (allotted_to IS NULL OR allotted_to >= allotted_from);
ALTER TABLE hostel_leave_requests ADD CONSTRAINT ck_hostel_leave_dates CHECK (to_date >= from_date);
ALTER TABLE hostel_complaints ADD CONSTRAINT ck_hostel_complaint_category CHECK (category IN ('MAINTENANCE','FOOD','SECURITY','OTHER'));
CREATE UNIQUE INDEX uq_hostel_active_student ON hostel_allotments(student_id) WHERE status='ACTIVE';
CREATE UNIQUE INDEX uq_hostel_active_bed ON hostel_allotments(room_id,bed_number) WHERE status='ACTIVE';
CREATE INDEX idx_hostel_attendance_tenant_date ON hostel_attendance(tenant_id,date);
CREATE INDEX idx_hostel_leaves_tenant_status ON hostel_leave_requests(tenant_id,status);
CREATE INDEX idx_hostel_complaints_tenant_status ON hostel_complaints(tenant_id,status);
CREATE OR REPLACE FUNCTION validate_hostel_row() RETURNS TRIGGER LANGUAGE plpgsql AS $$ BEGIN
 IF TG_TABLE_NAME='hostel_rooms' AND NOT EXISTS(SELECT 1 FROM hostel_blocks b WHERE b.id=NEW.block_id AND b.tenant_id=NEW.tenant_id) THEN RAISE EXCEPTION 'Hostel room and block tenants differ'; END IF;
 IF TG_TABLE_NAME='hostel_allotments' AND (NOT EXISTS(SELECT 1 FROM hostel_rooms r WHERE r.id=NEW.room_id AND r.tenant_id=NEW.tenant_id) OR NOT EXISTS(SELECT 1 FROM users u WHERE u.id=NEW.student_id AND u.tenant_id=NEW.tenant_id) OR NEW.bed_number>(SELECT capacity FROM hostel_rooms WHERE id=NEW.room_id)) THEN RAISE EXCEPTION 'Invalid cross-tenant hostel allotment or bed'; END IF;
 IF TG_TABLE_NAME='hostel_attendance' AND NOT EXISTS(SELECT 1 FROM hostel_allotments a WHERE a.student_id=NEW.student_id AND a.room_id=NEW.room_id AND a.tenant_id=NEW.tenant_id AND a.status='ACTIVE') THEN RAISE EXCEPTION 'Attendance requires an active matching allotment'; END IF;
 RETURN NEW; END $$;
CREATE TRIGGER trg_validate_hostel_room BEFORE INSERT OR UPDATE ON hostel_rooms FOR EACH ROW EXECUTE FUNCTION validate_hostel_row();
CREATE TRIGGER trg_validate_hostel_allotment BEFORE INSERT OR UPDATE ON hostel_allotments FOR EACH ROW EXECUTE FUNCTION validate_hostel_row();
CREATE TRIGGER trg_validate_hostel_attendance BEFORE INSERT OR UPDATE ON hostel_attendance FOR EACH ROW EXECUTE FUNCTION validate_hostel_row();
CREATE OR REPLACE FUNCTION refresh_hostel_block_counts() RETURNS TRIGGER LANGUAGE plpgsql AS $$ DECLARE target UUID:=COALESCE(NEW.block_id,OLD.block_id); BEGIN UPDATE hostel_blocks b SET total_rooms=(SELECT count(*) FROM hostel_rooms r WHERE r.block_id=target AND r.is_active),total_capacity=(SELECT coalesce(sum(capacity),0) FROM hostel_rooms r WHERE r.block_id=target AND r.is_active) WHERE id=target; IF TG_OP='UPDATE' AND OLD.block_id<>NEW.block_id THEN UPDATE hostel_blocks b SET total_rooms=(SELECT count(*) FROM hostel_rooms r WHERE r.block_id=OLD.block_id AND r.is_active),total_capacity=(SELECT coalesce(sum(capacity),0) FROM hostel_rooms r WHERE r.block_id=OLD.block_id AND r.is_active) WHERE id=OLD.block_id; END IF; IF TG_OP='DELETE' THEN RETURN OLD; END IF; RETURN NEW; END $$;
CREATE TRIGGER trg_refresh_hostel_block_counts AFTER INSERT OR UPDATE OR DELETE ON hostel_rooms FOR EACH ROW EXECUTE FUNCTION refresh_hostel_block_counts();
UPDATE hostel_blocks b SET total_rooms=(SELECT count(*) FROM hostel_rooms r WHERE r.block_id=b.id AND r.is_active),total_capacity=(SELECT coalesce(sum(capacity),0) FROM hostel_rooms r WHERE r.block_id=b.id AND r.is_active);
COMMIT;
