"""drift_check

Revision ID: 1438cd26b844
Revises: e1f2a3b4c5d6
Create Date: 2026-08-03 20:46:53.548216

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1438cd26b844'
down_revision: Union[str, None] = 'e1f2a3b4c5d6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_academic_events_academic_year_id', table_name='academic_events')
    op.drop_index('idx_academic_events_created_by', table_name='academic_events')
    op.drop_index('idx_answers_attempt', table_name='answers')
    op.drop_index('idx_answers_graded_by', table_name='answers')
    op.drop_index('idx_answers_question_id', table_name='answers')
    op.drop_index('idx_answers_selected_option_id', table_name='answers')
    op.drop_constraint('uq_answers__attempt_id_question_id', 'answers', type_='unique')
    op.create_index('uq_answers__attempt_id_question_id', 'answers', ['attempt_id', 'question_id'], unique=True)
    op.create_index('idx_answers_question', 'answers', ['question_id'], unique=False)
    op.alter_column('assignments', 'type',
               existing_type=postgresql.ENUM('REGULAR', 'MILESTONE', 'GROUP', name='assignment_type'),
               type_=sa.String(length=20),
               existing_nullable=False)
    op.alter_column('assignments', 'allowed_file_types',
               existing_type=postgresql.ARRAY(sa.TEXT()),
               type_=postgresql.ARRAY(sa.String()),
               existing_nullable=False,
               existing_server_default=sa.text("'{pdf,doc,docx,zip}'::text[]"))
    op.drop_index('idx_assignments_academic_year_id', table_name='assignments')
    op.drop_index('idx_assignments_subject_id', table_name='assignments')
    op.drop_index('idx_assignments_teacher_id', table_name='assignments')
    op.drop_index('idx_assignments_tenant_id', table_name='assignments')
    op.drop_index('idx_attendance_leaves_class_id', table_name='attendance_leaves')
    op.drop_index('idx_attendance_leaves_reviewed_by', table_name='attendance_leaves')
    op.drop_index('idx_attendance_leaves_student_id', table_name='attendance_leaves')
    op.drop_index('idx_attendance_leaves_tenant_id', table_name='attendance_leaves')
    op.create_index('idx_attendance_leaves_student', 'attendance_leaves', ['student_id'], unique=False)
    op.create_index('idx_attendance_leaves_tenant_class', 'attendance_leaves', ['tenant_id', 'class_id', 'status'], unique=False)
    op.drop_index('idx_att_records_student_date', table_name='attendance_records', postgresql_include=['session_id'])
    op.drop_index('idx_att_records_student_status', table_name='attendance_records')
    op.drop_index('idx_attendance_records_updated_by', table_name='attendance_records')
    op.drop_constraint('uq_attendance_records__session_id_student_id', 'attendance_records', type_='unique')
    op.drop_index('idx_att_sessions_teacher', table_name='attendance_sessions')
    op.drop_index('idx_attendance_sessions_academic_year_id', table_name='attendance_sessions')
    op.drop_index('idx_attendance_sessions_subject_id', table_name='attendance_sessions')
    op.drop_constraint('uq_attendance_sessions__tenant_id_subject_id_class_id_date_p', 'attendance_sessions', type_='unique')
    op.drop_index('idx_audit_created_at', table_name='audit_logs')
    op.drop_index('idx_audit_tenant_time', table_name='audit_logs')
    op.create_index('idx_audit_tenant_time', 'audit_logs', ['tenant_id', 'created_at'], unique=False)
    op.drop_constraint('audit_logs_tenant_id_fkey', 'audit_logs', type_='foreignkey')
    op.drop_index('idx_classes_academic_year_id', table_name='classes')
    op.drop_index('idx_classes_class_teacher_id', table_name='classes')
    op.drop_index('idx_classes_department_id', table_name='classes')
    op.drop_index('idx_content_access_logs_content_id', table_name='content_access_logs')
    op.drop_index('idx_content_access_logs_user_id', table_name='content_access_logs')
    op.create_index('idx_content_access_content', 'content_access_logs', ['content_id', 'accessed_at'], unique=False)
    op.drop_index('idx_content_chapter', table_name='content_items')
    op.drop_index('idx_content_items_class_id', table_name='content_items')
    op.drop_index('idx_content_items_tenant_id', table_name='content_items')
    op.drop_index('idx_content_items_uploaded_by', table_name='content_items')
    op.drop_index('idx_content_subject_class', table_name='content_items')
    op.create_index('idx_content_items_class_subject', 'content_items', ['class_id', 'subject_id', 'is_visible'], unique=False)
    op.create_index('idx_content_items_tenant', 'content_items', ['tenant_id'], unique=False)
    op.drop_constraint('uq_content_tags__content_id_tag', 'content_tags', type_='unique')
    op.create_index('uq_content_tags__content_id_tag', 'content_tags', ['content_id', 'tag'], unique=True)
    op.drop_index('idx_departments_hod_id', table_name='departments')
    op.drop_index('idx_discussion_replies_author_id', table_name='discussion_replies')
    op.drop_index('idx_discussion_replies_tenant_id', table_name='discussion_replies')
    op.drop_index('idx_replies_thread', table_name='discussion_replies')
    op.create_index('idx_discussion_replies_tenant', 'discussion_replies', ['tenant_id'], unique=False)
    op.create_index('idx_discussion_replies_thread', 'discussion_replies', ['thread_id', 'created_at'], unique=False)
    op.alter_column('discussion_threads', 'tags',
               existing_type=postgresql.ARRAY(sa.TEXT()),
               type_=postgresql.ARRAY(sa.String()),
               existing_nullable=True)
    op.drop_index('idx_discussion_threads_author_id', table_name='discussion_threads')
    op.drop_index('idx_discussion_threads_resolved_by', table_name='discussion_threads')
    op.drop_index('idx_discussion_threads_tenant_id', table_name='discussion_threads')
    op.drop_index('idx_threads_scope', table_name='discussion_threads')
    op.create_index('idx_threads_scope', 'discussion_threads', ['scope_type', 'scope_id', 'created_at'], unique=False)
    op.drop_constraint('uq_discussion_votes__user_id_target_type_target_id', 'discussion_votes', type_='unique')
    op.create_index('uq_discussion_votes__user_id_target_type_target_id', 'discussion_votes', ['user_id', 'target_type', 'target_id'], unique=True)
    op.alter_column('exam_attempts', 'ip_address',
               existing_type=postgresql.INET(),
               type_=sa.String(length=64),
               existing_nullable=True)
    op.drop_constraint('uq_exam_attempts__exam_id_student_id', 'exam_attempts', type_='unique')
    op.drop_index('idx_ec_grade_cards_class_id', table_name='exam_controller_grade_cards')
    op.drop_index('idx_ec_grade_cards_student_id', table_name='exam_controller_grade_cards')
    op.drop_index('idx_grade_cards_tenant_pub', table_name='exam_controller_grade_cards')
    op.drop_index('idx_ec_publications_academic_year_id', table_name='exam_controller_publications')
    op.drop_index('idx_ec_publications_class_id', table_name='exam_controller_publications')
    op.drop_index('idx_ec_publications_compiled_by', table_name='exam_controller_publications')
    op.drop_index('idx_exam_sections_exam_id', table_name='exam_sections')
    op.create_index('idx_exam_sections_exam', 'exam_sections', ['exam_id', 'sort_order'], unique=False)
    op.alter_column('exams', 'exam_type',
               existing_type=postgresql.ENUM('MCQ', 'DESCRIPTIVE', 'MIXED', 'QUIZ', name='exam_type'),
               type_=sa.String(length=20),
               existing_nullable=False)
    op.alter_column('exams', 'mode',
               existing_type=postgresql.ENUM('ONLINE', 'OFFLINE', name='exam_mode'),
               type_=sa.String(length=20),
               existing_nullable=False,
               existing_server_default=sa.text("'ONLINE'::exam_mode"))
    op.drop_index('idx_exams_academic_year_id', table_name='exams')
    op.drop_index('idx_exams_created_by', table_name='exams')
    op.drop_index('idx_exams_schedule_approved_by', table_name='exams')
    op.drop_index('idx_exams_subject_id', table_name='exams')
    op.drop_index('idx_exams_tenant_id', table_name='exams')
    op.alter_column('leave_requests', 'status',
               existing_type=postgresql.ENUM('PENDING', 'APPROVED', 'REJECTED', 'CANCELLED', name='leave_status'),
               type_=sa.String(length=20),
               existing_nullable=False,
               existing_server_default=sa.text("'PENDING'::leave_status"))
    op.drop_index('idx_leave_requests_policy_id', table_name='leave_requests')
    op.drop_index('idx_leave_requests_reviewed_by', table_name='leave_requests')
    op.drop_index('idx_leave_requests_staff_id', table_name='leave_requests')
    op.drop_index('idx_leave_requests_tenant_id', table_name='leave_requests')
    op.drop_constraint('leave_requests_policy_id_fkey', 'leave_requests', type_='foreignkey')
    op.drop_column('leave_requests', 'policy_id')
    op.drop_column('leave_requests', 'document_key')
    op.drop_index('idx_malpractice_logs_attempt_id', table_name='malpractice_logs')
    op.drop_index('idx_malpractice_logs_handled_by', table_name='malpractice_logs')
    op.drop_index('idx_malpractice_logs_student_id', table_name='malpractice_logs')
    op.drop_index('idx_malpractice_logs_tenant_id', table_name='malpractice_logs')
    op.create_index('idx_malpractice_tenant_logged', 'malpractice_logs', ['tenant_id', 'logged_at'], unique=False)
    op.drop_index('idx_mentor_assignments_academic_year_id', table_name='mentor_assignments')
    op.drop_index('idx_mentor_assignments_assigned_by', table_name='mentor_assignments')
    op.drop_index('idx_mentor_assignments_tenant_id', table_name='mentor_assignments')
    op.drop_constraint('uq_mentor_assignments__mentor_id_student_id_academic_year_id', 'mentor_assignments', type_='unique')
    op.drop_index('idx_milestones_assignment_id', table_name='milestones')
    op.drop_index('idx_milestones_unlock_after_milestone_id', table_name='milestones')
    op.create_index('idx_milestones_assignment', 'milestones', ['assignment_id', 'sort_order'], unique=False)
    op.drop_index('idx_notice_reads_user_id', table_name='notice_reads')
    op.drop_constraint('uq_notice_reads__notice_id_user_id', 'notice_reads', type_='unique')
    op.create_index('uq_notice_reads__notice_id_user_id', 'notice_reads', ['notice_id', 'user_id'], unique=True)
    op.drop_index('idx_notices_author_id', table_name='notices')
    op.drop_index('idx_orders_owner_id', table_name='orders')
    op.drop_index('idx_orders_tenant_id', table_name='orders')
    op.drop_index('idx_outbox_emails_tenant_id', table_name='outbox_emails')
    op.drop_index('idx_platform_invoice_lines_invoice_id', table_name='platform_invoice_lines')
    op.drop_index('idx_platform_invoices_subscription_id', table_name='platform_invoices')
    op.drop_index('idx_platform_payments_invoice_id', table_name='platform_payments')
    op.drop_index('idx_platform_payments_order_id', table_name='platform_payments')
    op.drop_index('idx_platform_users_role', table_name='platform_users')
    op.drop_index('idx_question_options_question_id', table_name='question_options')
    op.create_index('idx_question_options_question', 'question_options', ['question_id', 'sort_order'], unique=False)
    op.drop_index('idx_questions_section_id', table_name='questions')
    op.drop_index('idx_result_publications_academic_year_id', table_name='result_publications')
    op.drop_index('idx_result_publications_approved_by', table_name='result_publications')
    op.drop_index('idx_result_publications_class_id', table_name='result_publications')
    op.drop_index('idx_result_publications_published_by', table_name='result_publications')
    op.drop_index('idx_result_publications_tenant_id', table_name='result_publications')
    op.drop_index('idx_result_publications_tenant_approval', table_name='result_publications')
    op.create_index('idx_result_publications_tenant_approval', 'result_publications', ['tenant_id', 'approval_status', 'published_at'], unique=False)
    op.drop_index('idx_role_assignments_assigned_by', table_name='role_assignments')
    op.drop_index('idx_role_assignments_role_id', table_name='role_assignments')
    op.drop_index('idx_roles_module_key', table_name='roles')
    op.alter_column('staff_profiles', 'employment_type',
               existing_type=postgresql.ENUM('FULL_TIME', 'PART_TIME', 'CONTRACT', 'VISITING', name='employment_type'),
               type_=sa.String(length=20),
               existing_nullable=False)
    op.alter_column('staff_profiles', 'experience_years',
               existing_type=sa.SMALLINT(),
               type_=sa.Integer(),
               existing_nullable=False,
               existing_server_default=sa.text('0'))
    op.drop_index('idx_staff_profiles_department_id', table_name='staff_profiles')
    op.drop_index('idx_staff_profiles_tenant_id', table_name='staff_profiles')
    op.drop_column('staff_profiles', 'bank_name')
    op.drop_column('staff_profiles', 'created_at')
    op.drop_column('staff_profiles', 'emergency_contact_name')
    op.drop_column('staff_profiles', 'updated_at')
    op.drop_column('staff_profiles', 'bank_ifsc')
    op.drop_column('staff_profiles', 'emergency_contact_phone')
    op.drop_column('staff_profiles', 'bank_account_no')
    op.drop_column('staff_profiles', 'pan_number')
    op.drop_column('staff_profiles', 'pf_number')
    op.drop_index('idx_student_enrollments_academic_year_id', table_name='student_enrollments')
    op.drop_index('idx_student_enrollments_transferred_to', table_name='student_enrollments')
    op.drop_index('idx_student_results_class_id', table_name='student_results')
    op.drop_index('idx_student_results_tenant_id', table_name='student_results')
    op.drop_constraint('uq_student_results__publication_id_student_id', 'student_results', type_='unique')
    op.drop_index('idx_subjects_class_id', table_name='subjects')
    op.drop_index('idx_submission_files_submission_id', table_name='submission_files')
    op.create_index('idx_submission_files_submission', 'submission_files', ['submission_id'], unique=False)
    op.drop_index('idx_submission_reviews_reviewer_id', table_name='submission_reviews')
    op.drop_index('idx_submission_reviews_submission_id', table_name='submission_reviews')
    op.drop_index('idx_submission_reviews_tenant_id', table_name='submission_reviews')
    op.drop_constraint('uq_submission_reviews__submission_id_attempt_number', 'submission_reviews', type_='unique')
    op.create_index('uq_submission_reviews__submission_id_attempt_number', 'submission_reviews', ['submission_id', 'attempt_number'], unique=True)
    op.drop_index('idx_submissions_milestone_id', table_name='submissions')
    op.drop_index('idx_submissions_reviewed_by', table_name='submissions')
    op.drop_index('idx_submissions_status', table_name='submissions')
    op.drop_index('idx_submissions_student_id', table_name='submissions')
    op.drop_index('idx_submissions_tenant_id', table_name='submissions')
    op.drop_constraint('uq_submissions__assignment_id_milestone_id_student_id_ve', 'submissions', type_='unique')
    op.drop_index('idx_subscriptions_plan_id', table_name='subscriptions')
    op.drop_index('idx_subscriptions_status', table_name='subscriptions')
    op.drop_index('idx_subscriptions_tenant_created', table_name='subscriptions')
    op.alter_column('support_tickets', 'owner_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_index('idx_support_tickets_created_at', table_name='support_tickets')
    op.drop_index('idx_support_tickets_owner_id', table_name='support_tickets')
    op.drop_index('idx_support_tickets_priority', table_name='support_tickets')
    op.drop_index('idx_support_tickets_raised_by', table_name='support_tickets')
    op.drop_index('idx_support_tickets_tenant_status', table_name='support_tickets')
    op.drop_index('idx_teacher_subjects_assigned_by', table_name='teacher_subjects')
    op.drop_index('idx_tenant_modules_disabled_by', table_name='tenant_modules')
    op.drop_index('idx_tenant_modules_enabled_by', table_name='tenant_modules')
    op.drop_index('idx_tenant_modules_module_key', table_name='tenant_modules')
    op.drop_index('idx_tm_tenant_enabled', table_name='tenant_modules')
    op.drop_index('idx_tenants_created_at', table_name='tenants')
    op.drop_index('idx_tenants_is_active', table_name='tenants')
    op.drop_index('idx_tenants_owner_id', table_name='tenants')
    op.drop_index('idx_tenants_owner_platform_user_id', table_name='tenants')
    op.drop_index('idx_tenants_plan_id', table_name='tenants')
    op.drop_constraint('tenants_owner_id_fkey', 'tenants', type_='foreignkey')
    op.alter_column('timetable_slots', 'day_of_week',
               existing_type=sa.SMALLINT(),
               type_=sa.Integer(),
               existing_nullable=False)
    op.alter_column('timetable_slots', 'period_number',
               existing_type=sa.SMALLINT(),
               type_=sa.Integer(),
               existing_nullable=False)
    op.alter_column('timetable_slots', 'slot_type',
               existing_type=postgresql.ENUM('CLASS', 'BREAK', 'LAB', 'ACTIVITY', name='slot_type'),
               type_=sa.String(length=20),
               existing_nullable=False,
               existing_server_default=sa.text("'CLASS'::slot_type"))
    op.drop_index('idx_timetable_slots_academic_year_id', table_name='timetable_slots')
    op.drop_index('idx_timetable_slots_subject_id', table_name='timetable_slots')
    op.drop_index('idx_timetable_slots_tenant_id', table_name='timetable_slots')
    op.drop_index('idx_timetable_teacher', table_name='timetable_slots')
    op.drop_constraint('uq_timetable_slots__class_id_day_of_week_period_number_effec', 'timetable_slots', type_='unique')
    op.drop_index('idx_timetable_substitutions_arranged_by', table_name='timetable_substitutions')
    op.drop_index('idx_timetable_substitutions_original_teacher_id', table_name='timetable_substitutions')
    op.drop_index('idx_timetable_substitutions_substitute_teacher_id', table_name='timetable_substitutions')
    op.drop_constraint('uq_timetable_substitutions__slot_id_date', 'timetable_substitutions', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_timetable_substitutions__slot_id_date', 'timetable_substitutions', ['slot_id', 'date'])
    op.create_index('idx_timetable_substitutions_substitute_teacher_id', 'timetable_substitutions', ['substitute_teacher_id'], unique=False)
    op.create_index('idx_timetable_substitutions_original_teacher_id', 'timetable_substitutions', ['original_teacher_id'], unique=False)
    op.create_index('idx_timetable_substitutions_arranged_by', 'timetable_substitutions', ['arranged_by'], unique=False)
    op.create_unique_constraint('uq_timetable_slots__class_id_day_of_week_period_number_effec', 'timetable_slots', ['class_id', 'day_of_week', 'period_number', 'effective_from'])
    op.create_index('idx_timetable_teacher', 'timetable_slots', ['teacher_id'], unique=False)
    op.create_index('idx_timetable_slots_tenant_id', 'timetable_slots', ['tenant_id'], unique=False)
    op.create_index('idx_timetable_slots_subject_id', 'timetable_slots', ['subject_id'], unique=False)
    op.create_index('idx_timetable_slots_academic_year_id', 'timetable_slots', ['academic_year_id'], unique=False)
    op.alter_column('timetable_slots', 'slot_type',
               existing_type=sa.String(length=20),
               type_=postgresql.ENUM('CLASS', 'BREAK', 'LAB', 'ACTIVITY', name='slot_type'),
               existing_nullable=False,
               existing_server_default=sa.text("'CLASS'::slot_type"))
    op.alter_column('timetable_slots', 'period_number',
               existing_type=sa.Integer(),
               type_=sa.SMALLINT(),
               existing_nullable=False)
    op.alter_column('timetable_slots', 'day_of_week',
               existing_type=sa.Integer(),
               type_=sa.SMALLINT(),
               existing_nullable=False)
    op.create_foreign_key('tenants_owner_id_fkey', 'tenants', 'platform_owners', ['owner_id'], ['id'], ondelete='SET NULL')
    op.create_index('idx_tenants_plan_id', 'tenants', ['plan_id'], unique=False)
    op.create_index('idx_tenants_owner_platform_user_id', 'tenants', ['owner_platform_user_id'], unique=False)
    op.create_index('idx_tenants_owner_id', 'tenants', ['owner_id'], unique=False)
    op.create_index('idx_tenants_is_active', 'tenants', ['is_active'], unique=False)
    op.create_index('idx_tenants_created_at', 'tenants', [sa.text('created_at DESC')], unique=False)
    op.create_index('idx_tm_tenant_enabled', 'tenant_modules', ['tenant_id', 'is_enabled'], unique=False)
    op.create_index('idx_tenant_modules_module_key', 'tenant_modules', ['module_key'], unique=False)
    op.create_index('idx_tenant_modules_enabled_by', 'tenant_modules', ['enabled_by'], unique=False)
    op.create_index('idx_tenant_modules_disabled_by', 'tenant_modules', ['disabled_by'], unique=False)
    op.create_index('idx_teacher_subjects_assigned_by', 'teacher_subjects', ['assigned_by'], unique=False)
    op.create_index('idx_support_tickets_tenant_status', 'support_tickets', ['tenant_id', 'status'], unique=False)
    op.create_index('idx_support_tickets_raised_by', 'support_tickets', ['raised_by'], unique=False)
    op.create_index('idx_support_tickets_priority', 'support_tickets', ['priority'], unique=False)
    op.create_index('idx_support_tickets_owner_id', 'support_tickets', ['owner_id'], unique=False)
    op.create_index('idx_support_tickets_created_at', 'support_tickets', [sa.text('created_at DESC')], unique=False)
    op.alter_column('support_tickets', 'owner_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.create_index('idx_subscriptions_tenant_created', 'subscriptions', ['tenant_id', sa.text('created_at DESC')], unique=False)
    op.create_index('idx_subscriptions_status', 'subscriptions', ['status'], unique=False)
    op.create_index('idx_subscriptions_plan_id', 'subscriptions', ['plan_id'], unique=False)
    op.create_unique_constraint('uq_submissions__assignment_id_milestone_id_student_id_ve', 'submissions', ['assignment_id', 'milestone_id', 'student_id', 'version'])
    op.create_index('idx_submissions_tenant_id', 'submissions', ['tenant_id'], unique=False)
    op.create_index('idx_submissions_student_id', 'submissions', ['student_id'], unique=False)
    op.create_index('idx_submissions_status', 'submissions', ['status'], unique=False)
    op.create_index('idx_submissions_reviewed_by', 'submissions', ['reviewed_by'], unique=False)
    op.create_index('idx_submissions_milestone_id', 'submissions', ['milestone_id'], unique=False)
    op.drop_index('uq_submission_reviews__submission_id_attempt_number', table_name='submission_reviews')
    op.create_unique_constraint('uq_submission_reviews__submission_id_attempt_number', 'submission_reviews', ['submission_id', 'attempt_number'])
    op.create_index('idx_submission_reviews_tenant_id', 'submission_reviews', ['tenant_id'], unique=False)
    op.create_index('idx_submission_reviews_submission_id', 'submission_reviews', ['submission_id', sa.text('attempt_number DESC')], unique=False)
    op.create_index('idx_submission_reviews_reviewer_id', 'submission_reviews', ['reviewer_id'], unique=False)
    op.drop_index('idx_submission_files_submission', table_name='submission_files')
    op.create_index('idx_submission_files_submission_id', 'submission_files', ['submission_id'], unique=False)
    op.create_index('idx_subjects_class_id', 'subjects', ['class_id'], unique=False)
    op.create_unique_constraint('uq_student_results__publication_id_student_id', 'student_results', ['publication_id', 'student_id'])
    op.create_index('idx_student_results_tenant_id', 'student_results', ['tenant_id'], unique=False)
    op.create_index('idx_student_results_class_id', 'student_results', ['class_id'], unique=False)
    op.create_index('idx_student_enrollments_transferred_to', 'student_enrollments', ['transferred_to'], unique=False)
    op.create_index('idx_student_enrollments_academic_year_id', 'student_enrollments', ['academic_year_id'], unique=False)
    op.add_column('staff_profiles', sa.Column('pf_number', sa.VARCHAR(length=30), autoincrement=False, nullable=True))
    op.add_column('staff_profiles', sa.Column('pan_number', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.add_column('staff_profiles', sa.Column('bank_account_no', sa.VARCHAR(length=30), autoincrement=False, nullable=True))
    op.add_column('staff_profiles', sa.Column('emergency_contact_phone', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.add_column('staff_profiles', sa.Column('bank_ifsc', sa.VARCHAR(length=15), autoincrement=False, nullable=True))
    op.add_column('staff_profiles', sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.add_column('staff_profiles', sa.Column('emergency_contact_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('staff_profiles', sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.add_column('staff_profiles', sa.Column('bank_name', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.create_index('idx_staff_profiles_tenant_id', 'staff_profiles', ['tenant_id'], unique=False)
    op.create_index('idx_staff_profiles_department_id', 'staff_profiles', ['department_id'], unique=False)
    op.alter_column('staff_profiles', 'experience_years',
               existing_type=sa.Integer(),
               type_=sa.SMALLINT(),
               existing_nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('staff_profiles', 'employment_type',
               existing_type=sa.String(length=20),
               type_=postgresql.ENUM('FULL_TIME', 'PART_TIME', 'CONTRACT', 'VISITING', name='employment_type'),
               existing_nullable=False)
    op.create_index('idx_roles_module_key', 'roles', ['module_key'], unique=False)
    op.create_index('idx_role_assignments_role_id', 'role_assignments', ['role_id'], unique=False)
    op.create_index('idx_role_assignments_assigned_by', 'role_assignments', ['assigned_by'], unique=False)
    op.drop_index('idx_result_publications_tenant_approval', table_name='result_publications')
    op.create_index('idx_result_publications_tenant_approval', 'result_publications', ['tenant_id', 'approval_status', sa.text('published_at DESC')], unique=False)
    op.create_index('idx_result_publications_tenant_id', 'result_publications', ['tenant_id'], unique=False)
    op.create_index('idx_result_publications_published_by', 'result_publications', ['published_by'], unique=False)
    op.create_index('idx_result_publications_class_id', 'result_publications', ['class_id'], unique=False)
    op.create_index('idx_result_publications_approved_by', 'result_publications', ['approved_by'], unique=False)
    op.create_index('idx_result_publications_academic_year_id', 'result_publications', ['academic_year_id'], unique=False)
    op.create_index('idx_questions_section_id', 'questions', ['section_id'], unique=False)
    op.drop_index('idx_question_options_question', table_name='question_options')
    op.create_index('idx_question_options_question_id', 'question_options', ['question_id'], unique=False)
    op.create_index('idx_platform_users_role', 'platform_users', ['platform_role'], unique=False)
    op.create_index('idx_platform_payments_order_id', 'platform_payments', ['order_id'], unique=False)
    op.create_index('idx_platform_payments_invoice_id', 'platform_payments', ['invoice_id'], unique=False)
    op.create_index('idx_platform_invoices_subscription_id', 'platform_invoices', ['subscription_id'], unique=False)
    op.create_index('idx_platform_invoice_lines_invoice_id', 'platform_invoice_lines', ['invoice_id'], unique=False)
    op.create_index('idx_outbox_emails_tenant_id', 'outbox_emails', ['tenant_id'], unique=False)
    op.create_index('idx_orders_tenant_id', 'orders', ['tenant_id'], unique=False)
    op.create_index('idx_orders_owner_id', 'orders', ['owner_id'], unique=False)
    op.create_index('idx_notices_author_id', 'notices', ['author_id'], unique=False)
    op.drop_index('uq_notice_reads__notice_id_user_id', table_name='notice_reads')
    op.create_unique_constraint('uq_notice_reads__notice_id_user_id', 'notice_reads', ['notice_id', 'user_id'])
    op.create_index('idx_notice_reads_user_id', 'notice_reads', ['user_id'], unique=False)
    op.drop_index('idx_milestones_assignment', table_name='milestones')
    op.create_index('idx_milestones_unlock_after_milestone_id', 'milestones', ['unlock_after_milestone_id'], unique=False)
    op.create_index('idx_milestones_assignment_id', 'milestones', ['assignment_id'], unique=False)
    op.create_unique_constraint('uq_mentor_assignments__mentor_id_student_id_academic_year_id', 'mentor_assignments', ['mentor_id', 'student_id', 'academic_year_id'])
    op.create_index('idx_mentor_assignments_tenant_id', 'mentor_assignments', ['tenant_id'], unique=False)
    op.create_index('idx_mentor_assignments_assigned_by', 'mentor_assignments', ['assigned_by'], unique=False)
    op.create_index('idx_mentor_assignments_academic_year_id', 'mentor_assignments', ['academic_year_id'], unique=False)
    op.drop_index('idx_malpractice_tenant_logged', table_name='malpractice_logs')
    op.create_index('idx_malpractice_logs_tenant_id', 'malpractice_logs', ['tenant_id'], unique=False)
    op.create_index('idx_malpractice_logs_student_id', 'malpractice_logs', ['student_id'], unique=False)
    op.create_index('idx_malpractice_logs_handled_by', 'malpractice_logs', ['handled_by'], unique=False)
    op.create_index('idx_malpractice_logs_attempt_id', 'malpractice_logs', ['attempt_id'], unique=False)
    op.add_column('leave_requests', sa.Column('document_key', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('leave_requests', sa.Column('policy_id', sa.UUID(), autoincrement=False, nullable=False))
    op.create_foreign_key('leave_requests_policy_id_fkey', 'leave_requests', 'leave_policies', ['policy_id'], ['id'])
    op.create_index('idx_leave_requests_tenant_id', 'leave_requests', ['tenant_id'], unique=False)
    op.create_index('idx_leave_requests_staff_id', 'leave_requests', ['staff_id'], unique=False)
    op.create_index('idx_leave_requests_reviewed_by', 'leave_requests', ['reviewed_by'], unique=False)
    op.create_index('idx_leave_requests_policy_id', 'leave_requests', ['policy_id'], unique=False)
    op.alter_column('leave_requests', 'status',
               existing_type=sa.String(length=20),
               type_=postgresql.ENUM('PENDING', 'APPROVED', 'REJECTED', 'CANCELLED', name='leave_status'),
               existing_nullable=False,
               existing_server_default=sa.text("'PENDING'::leave_status"))
    op.create_index('idx_exams_tenant_id', 'exams', ['tenant_id'], unique=False)
    op.create_index('idx_exams_subject_id', 'exams', ['subject_id'], unique=False)
    op.create_index('idx_exams_schedule_approved_by', 'exams', ['schedule_approved_by'], unique=False)
    op.create_index('idx_exams_created_by', 'exams', ['created_by'], unique=False)
    op.create_index('idx_exams_academic_year_id', 'exams', ['academic_year_id'], unique=False)
    op.alter_column('exams', 'mode',
               existing_type=sa.String(length=20),
               type_=postgresql.ENUM('ONLINE', 'OFFLINE', name='exam_mode'),
               existing_nullable=False,
               existing_server_default=sa.text("'ONLINE'::exam_mode"))
    op.alter_column('exams', 'exam_type',
               existing_type=sa.String(length=20),
               type_=postgresql.ENUM('MCQ', 'DESCRIPTIVE', 'MIXED', 'QUIZ', name='exam_type'),
               existing_nullable=False)
    op.drop_index('idx_exam_sections_exam', table_name='exam_sections')
    op.create_index('idx_exam_sections_exam_id', 'exam_sections', ['exam_id'], unique=False)
    op.create_index('idx_ec_publications_compiled_by', 'exam_controller_publications', ['compiled_by'], unique=False)
    op.create_index('idx_ec_publications_class_id', 'exam_controller_publications', ['class_id'], unique=False)
    op.create_index('idx_ec_publications_academic_year_id', 'exam_controller_publications', ['academic_year_id'], unique=False)
    op.create_index('idx_grade_cards_tenant_pub', 'exam_controller_grade_cards', ['tenant_id', 'publication_id'], unique=False)
    op.create_index('idx_ec_grade_cards_student_id', 'exam_controller_grade_cards', ['student_id'], unique=False)
    op.create_index('idx_ec_grade_cards_class_id', 'exam_controller_grade_cards', ['class_id'], unique=False)
    op.create_unique_constraint('uq_exam_attempts__exam_id_student_id', 'exam_attempts', ['exam_id', 'student_id'])
    op.alter_column('exam_attempts', 'ip_address',
               existing_type=sa.String(length=64),
               type_=postgresql.INET(),
               existing_nullable=True)
    op.drop_index('uq_discussion_votes__user_id_target_type_target_id', table_name='discussion_votes')
    op.create_unique_constraint('uq_discussion_votes__user_id_target_type_target_id', 'discussion_votes', ['user_id', 'target_type', 'target_id'])
    op.drop_index('idx_threads_scope', table_name='discussion_threads')
    op.create_index('idx_threads_scope', 'discussion_threads', ['scope_type', 'scope_id', sa.text('created_at DESC')], unique=False)
    op.create_index('idx_discussion_threads_tenant_id', 'discussion_threads', ['tenant_id'], unique=False)
    op.create_index('idx_discussion_threads_resolved_by', 'discussion_threads', ['resolved_by'], unique=False)
    op.create_index('idx_discussion_threads_author_id', 'discussion_threads', ['author_id'], unique=False)
    op.alter_column('discussion_threads', 'tags',
               existing_type=postgresql.ARRAY(sa.String()),
               type_=postgresql.ARRAY(sa.TEXT()),
               existing_nullable=True)
    op.drop_index('idx_discussion_replies_thread', table_name='discussion_replies')
    op.drop_index('idx_discussion_replies_tenant', table_name='discussion_replies')
    op.create_index('idx_replies_thread', 'discussion_replies', ['thread_id', 'created_at'], unique=False)
    op.create_index('idx_discussion_replies_tenant_id', 'discussion_replies', ['tenant_id'], unique=False)
    op.create_index('idx_discussion_replies_author_id', 'discussion_replies', ['author_id'], unique=False)
    op.create_index('idx_departments_hod_id', 'departments', ['hod_id'], unique=False)
    op.drop_index('uq_content_tags__content_id_tag', table_name='content_tags')
    op.create_unique_constraint('uq_content_tags__content_id_tag', 'content_tags', ['content_id', 'tag'])
    op.drop_index('idx_content_items_tenant', table_name='content_items')
    op.drop_index('idx_content_items_class_subject', table_name='content_items')
    op.create_index('idx_content_subject_class', 'content_items', ['subject_id', 'class_id', 'is_visible'], unique=False)
    op.create_index('idx_content_items_uploaded_by', 'content_items', ['uploaded_by'], unique=False)
    op.create_index('idx_content_items_tenant_id', 'content_items', ['tenant_id'], unique=False)
    op.create_index('idx_content_items_class_id', 'content_items', ['class_id'], unique=False)
    op.create_index('idx_content_chapter', 'content_items', ['subject_id', 'chapter'], unique=False)
    op.drop_index('idx_content_access_content', table_name='content_access_logs')
    op.create_index('idx_content_access_logs_user_id', 'content_access_logs', ['user_id'], unique=False)
    op.create_index('idx_content_access_logs_content_id', 'content_access_logs', ['content_id'], unique=False)
    op.create_index('idx_classes_department_id', 'classes', ['department_id'], unique=False)
    op.create_index('idx_classes_class_teacher_id', 'classes', ['class_teacher_id'], unique=False)
    op.create_index('idx_classes_academic_year_id', 'classes', ['academic_year_id'], unique=False)
    op.create_foreign_key('audit_logs_tenant_id_fkey', 'audit_logs', 'tenants', ['tenant_id'], ['id'])
    op.drop_index('idx_audit_tenant_time', table_name='audit_logs')
    op.create_index('idx_audit_tenant_time', 'audit_logs', ['tenant_id', sa.text('created_at DESC')], unique=False)
    op.create_index('idx_audit_created_at', 'audit_logs', [sa.text('created_at DESC')], unique=False)
    op.create_unique_constraint('uq_attendance_sessions__tenant_id_subject_id_class_id_date_p', 'attendance_sessions', ['tenant_id', 'subject_id', 'class_id', 'date', 'period_label'])
    op.create_index('idx_attendance_sessions_subject_id', 'attendance_sessions', ['subject_id'], unique=False)
    op.create_index('idx_attendance_sessions_academic_year_id', 'attendance_sessions', ['academic_year_id'], unique=False)
    op.create_index('idx_att_sessions_teacher', 'attendance_sessions', ['teacher_id'], unique=False)
    op.create_unique_constraint('uq_attendance_records__session_id_student_id', 'attendance_records', ['session_id', 'student_id'])
    op.create_index('idx_attendance_records_updated_by', 'attendance_records', ['updated_by'], unique=False)
    op.create_index('idx_att_records_student_status', 'attendance_records', ['student_id', 'status'], unique=False)
    op.create_index('idx_att_records_student_date', 'attendance_records', ['tenant_id', 'student_id', 'status'], unique=False, postgresql_include=['session_id'])
    op.drop_index('idx_attendance_leaves_tenant_class', table_name='attendance_leaves')
    op.drop_index('idx_attendance_leaves_student', table_name='attendance_leaves')
    op.create_index('idx_attendance_leaves_tenant_id', 'attendance_leaves', ['tenant_id'], unique=False)
    op.create_index('idx_attendance_leaves_student_id', 'attendance_leaves', ['student_id'], unique=False)
    op.create_index('idx_attendance_leaves_reviewed_by', 'attendance_leaves', ['reviewed_by'], unique=False)
    op.create_index('idx_attendance_leaves_class_id', 'attendance_leaves', ['class_id'], unique=False)
    op.create_index('idx_assignments_tenant_id', 'assignments', ['tenant_id'], unique=False)
    op.create_index('idx_assignments_teacher_id', 'assignments', ['teacher_id'], unique=False)
    op.create_index('idx_assignments_subject_id', 'assignments', ['subject_id'], unique=False)
    op.create_index('idx_assignments_academic_year_id', 'assignments', ['academic_year_id'], unique=False)
    op.alter_column('assignments', 'allowed_file_types',
               existing_type=postgresql.ARRAY(sa.String()),
               type_=postgresql.ARRAY(sa.TEXT()),
               existing_nullable=False,
               existing_server_default=sa.text("'{pdf,doc,docx,zip}'::text[]"))
    op.alter_column('assignments', 'type',
               existing_type=sa.String(length=20),
               type_=postgresql.ENUM('REGULAR', 'MILESTONE', 'GROUP', name='assignment_type'),
               existing_nullable=False)
    op.drop_index('idx_answers_question', table_name='answers')
    op.drop_index('uq_answers__attempt_id_question_id', table_name='answers')
    op.create_unique_constraint('uq_answers__attempt_id_question_id', 'answers', ['attempt_id', 'question_id'])
    op.create_index('idx_answers_selected_option_id', 'answers', ['selected_option_id'], unique=False)
    op.create_index('idx_answers_question_id', 'answers', ['question_id'], unique=False)
    op.create_index('idx_answers_graded_by', 'answers', ['graded_by'], unique=False)
    op.create_index('idx_answers_attempt', 'answers', ['attempt_id'], unique=False)
    op.create_index('idx_academic_events_created_by', 'academic_events', ['created_by'], unique=False)
    op.create_index('idx_academic_events_academic_year_id', 'academic_events', ['academic_year_id'], unique=False)
    # ### end Alembic commands ###
