"""initial_schema

Revision ID: d606addfec08
Revises: 
Create Date: 2026-08-02 17:48:40.242689

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd606addfec08'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('coupons',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('discount_type', sa.String(length=10), nullable=False),
    sa.Column('value', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('max_uses', sa.Integer(), nullable=False),
    sa.Column('used_count', sa.Integer(), nullable=False),
    sa.Column('valid_from', sa.Date(), nullable=True),
    sa.Column('valid_until', sa.Date(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('modules',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('key', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_core', sa.Boolean(), nullable=False),
    sa.Column('icon', sa.String(length=50), nullable=True),
    sa.Column('price_monthly', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key')
    )
    op.create_table('orders',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('mode', sa.String(length=10), nullable=False),
    sa.Column('plan_slug', sa.String(length=50), nullable=False),
    sa.Column('module_keys', sa.ARRAY(sa.String(length=50)), nullable=False),
    sa.Column('billing_cycle', sa.String(length=10), nullable=False),
    sa.Column('subtotal', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('discount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('total', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('coupon_code', sa.String(length=50), nullable=True),
    sa.Column('institution_name', sa.String(length=255), nullable=False),
    sa.Column('institution_type', sa.String(length=20), nullable=False),
    sa.Column('contact_email', sa.String(length=255), nullable=False),
    sa.Column('owner_name', sa.String(length=255), nullable=True),
    sa.Column('owner_email', sa.String(length=255), nullable=True),
    sa.Column('owner_platform_user_id', sa.UUID(), nullable=True),
    sa.Column('contact_phone', sa.String(length=20), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=False),
    sa.Column('state', sa.String(length=100), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('url_slug', sa.String(length=100), nullable=False),
    sa.Column('owner_id', sa.UUID(), nullable=True),
    sa.Column('password_hash', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('payment_method', sa.String(length=20), nullable=True),
    sa.Column('gateway_ref', sa.String(length=255), nullable=True),
    sa.Column('tenant_id', sa.UUID(), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('paid_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_orders_contact_email', 'orders', ['contact_email'], unique=False)
    op.create_index('idx_orders_owner_platform_user_id', 'orders', ['owner_platform_user_id'], unique=False)
    op.create_index('idx_orders_status_created_at', 'orders', ['status', 'created_at'], unique=False)
    op.create_table('outbox_emails',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('event', sa.String(length=50), nullable=False),
    sa.Column('to_address', sa.String(length=255), nullable=False),
    sa.Column('subject', sa.String(length=255), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_outbox_emails_status', 'outbox_emails', ['status'], unique=False)
    op.create_table('plans',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('slug', sa.String(length=50), nullable=False),
    sa.Column('max_students', sa.Integer(), nullable=False),
    sa.Column('max_teachers', sa.Integer(), nullable=False),
    sa.Column('max_storage_gb', sa.Integer(), nullable=False),
    sa.Column('price_monthly', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('price_yearly', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('allowed_modules', sa.ARRAY(sa.String(length=50)), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('platform_owners',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('is_email_verified', sa.Boolean(), nullable=False),
    sa.Column('email_verification_token', sa.String(length=255), nullable=True),
    sa.Column('email_verification_expires', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('password_reset_token', sa.String(length=255), nullable=True),
    sa.Column('password_reset_expires', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_login_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index('idx_platform_owners_email', 'platform_owners', ['email'], unique=False)
    op.create_table('platform_users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.Text(), nullable=False),
    sa.Column('platform_role', sa.Enum('SUPER_ADMIN', 'SUPPORT', 'SALES', 'FINANCE', 'OWNER', name='platform_role'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('email_verified_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('email_verification_token_hash', sa.Text(), nullable=True),
    sa.Column('last_login_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('roles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('label', sa.String(length=100), nullable=False),
    sa.Column('scope_level', sa.Enum('PLATFORM', 'INSTITUTION', 'DEPARTMENT', 'CLASS', 'SUBJECT', 'SELF', 'CHILD', name='scope_level'), nullable=False),
    sa.Column('is_platform', sa.Boolean(), nullable=False),
    sa.Column('is_optional', sa.Boolean(), nullable=False),
    sa.Column('module_key', sa.String(length=50), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('service_requests',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('contact_name', sa.String(length=100), nullable=False),
    sa.Column('institution_name', sa.String(length=255), nullable=False),
    sa.Column('work_email', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=30), nullable=True),
    sa.Column('institution_type', sa.String(length=20), nullable=False),
    sa.Column('student_count', sa.Integer(), nullable=True),
    sa.Column('service_interest', sa.String(length=100), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), server_default=sa.text("'NEW'"), nullable=False),
    sa.Column('source', sa.String(length=100), server_default=sa.text("'website'"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('student_count IS NULL OR student_count > 0', name='ck_service_requests_student_count'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_service_requests_status_created_at', 'service_requests', ['status', 'created_at'], unique=False)
    op.create_index('idx_service_requests_work_email', 'service_requests', ['work_email'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('password_hash', sa.Text(), nullable=True),
    sa.Column('avatar_url', sa.Text(), nullable=True),
    sa.Column('gender', sa.Enum('MALE', 'FEMALE', 'OTHER', name='gender'), nullable=True),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('employee_code', sa.String(length=50), nullable=True),
    sa.Column('student_roll_no', sa.String(length=50), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('email_verified_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('phone_verified_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('last_login_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('password_reset_token', sa.String(length=255), nullable=True),
    sa.Column('password_reset_expires', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_users_deleted_at', 'users', ['deleted_at'], unique=False, postgresql_where='deleted_at IS NULL')
    op.create_index('idx_users_email', 'users', ['email'], unique=False, postgresql_where='email IS NOT NULL')
    op.create_index('idx_users_is_active', 'users', ['tenant_id', 'is_active'], unique=False)
    op.create_index('idx_users_tenant_id', 'users', ['tenant_id'], unique=False)
    op.create_index('uq_users__tenant_id_email', 'users', ['tenant_id', 'email'], unique=True, postgresql_where='email IS NOT NULL')
    op.create_index('uq_users__tenant_id_student_roll_no', 'users', ['tenant_id', 'student_roll_no'], unique=True, postgresql_where='student_roll_no IS NOT NULL')
    op.create_table('owner_sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('owner_id', sa.UUID(), nullable=False),
    sa.Column('refresh_token_hash', sa.String(length=255), nullable=False),
    sa.Column('device_info', sa.Text(), nullable=True),
    sa.Column('ip_address', postgresql.INET(), nullable=True),
    sa.Column('expires_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('revoked_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['platform_owners.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('refresh_token_hash')
    )
    op.create_index('idx_owner_sessions_expires_at', 'owner_sessions', ['expires_at'], unique=False)
    op.create_index('idx_owner_sessions_owner_id', 'owner_sessions', ['owner_id'], unique=False)
    op.create_table('permissions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('role_id', sa.UUID(), nullable=False),
    sa.Column('module_key', sa.String(length=50), nullable=False),
    sa.Column('action', sa.Enum('CREATE', 'READ', 'UPDATE', 'DELETE', name='permission_action'), nullable=False),
    sa.Column('scope', sa.Enum('ALL', 'DEPARTMENT', 'CLASS', 'SUBJECT', 'OWN', 'CHILD', name='permission_scope'), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('uq_permissions__role_id_module_key_action', 'permissions', ['role_id', 'module_key', 'action'], unique=True)
    op.create_table('platform_sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('refresh_token_hash', sa.String(length=255), nullable=False),
    sa.Column('device_info', sa.Text(), nullable=True),
    sa.Column('ip_address', postgresql.INET(), nullable=True),
    sa.Column('expires_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('revoked_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['platform_users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('refresh_token_hash')
    )
    op.create_index('idx_platform_sessions_expires_at', 'platform_sessions', ['expires_at'], unique=False)
    op.create_index('idx_platform_sessions_user_id', 'platform_sessions', ['user_id'], unique=False)
    op.create_table('tenants',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('type', sa.Enum('SCHOOL', 'COLLEGE', name='tenant_type'), nullable=False),
    sa.Column('plan_id', sa.UUID(), nullable=True),
    sa.Column('owner_id', sa.UUID(), nullable=True),
    sa.Column('owner_platform_user_id', sa.UUID(), nullable=True),
    sa.Column('logo_url', sa.Text(), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('state', sa.String(length=100), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=False),
    sa.Column('pincode', sa.String(length=20), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('website', sa.String(length=255), nullable=True),
    sa.Column('timezone', sa.String(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('trial_ends_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['platform_owners.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['owner_platform_user_id'], ['platform_users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('user_sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('refresh_token_hash', sa.String(length=255), nullable=False),
    sa.Column('device_info', sa.Text(), nullable=True),
    sa.Column('ip_address', postgresql.INET(), nullable=True),
    sa.Column('expires_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('revoked_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('refresh_token_hash')
    )
    op.create_index('idx_user_sessions_expires_at', 'user_sessions', ['expires_at'], unique=False)
    op.create_index('idx_user_sessions_user_id', 'user_sessions', ['user_id'], unique=False)
    op.create_table('academic_years',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'name', name='uq_academic_years__tenant_id_name')
    )
    op.create_index('idx_academic_years_tenant_id', 'academic_years', ['tenant_id'], unique=False)
    op.create_table('departments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('hod_id', sa.UUID(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'code', name='uq_departments__tenant_id_code')
    )
    op.create_index('idx_departments_tenant_id', 'departments', ['tenant_id'], unique=False)
    op.create_table('platform_invoices',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('subscription_id', sa.UUID(), nullable=True),
    sa.Column('invoice_number', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('issued_at', sa.Date(), nullable=False),
    sa.Column('due_at', sa.Date(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('subtotal', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('tax_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('total', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('amount_paid', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('gstin', sa.String(length=15), nullable=True),
    sa.Column('place_of_supply', sa.String(length=2), nullable=True),
    sa.Column('pdf_key', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('invoice_number')
    )
    op.create_index('idx_platform_invoices_tenant_id', 'platform_invoices', ['tenant_id'], unique=False)
    op.create_table('platform_payments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=True),
    sa.Column('invoice_id', sa.UUID(), nullable=True),
    sa.Column('order_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('method', sa.String(length=20), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('gateway', sa.String(length=50), nullable=True),
    sa.Column('gateway_ref', sa.String(length=255), nullable=True),
    sa.Column('failure_reason', sa.Text(), nullable=True),
    sa.Column('received_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_platform_payments_tenant_id', 'platform_payments', ['tenant_id'], unique=False)
    op.create_table('role_assignments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('role_id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('scope_id', sa.UUID(), nullable=True),
    sa.Column('scope_type', sa.String(length=50), nullable=True),
    sa.Column('assigned_by', sa.UUID(), nullable=True),
    sa.Column('assigned_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['assigned_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_ra_scope_id', 'role_assignments', ['scope_id'], unique=False, postgresql_where='scope_id IS NOT NULL')
    op.create_index('idx_ra_tenant_role', 'role_assignments', ['tenant_id', 'role_id'], unique=False)
    op.create_index('idx_ra_user_id', 'role_assignments', ['user_id'], unique=False)
    op.create_index('uq_role_assignments__user_role_tenant_scope', 'role_assignments', ['user_id', 'role_id', 'tenant_id', 'scope_id'], unique=True)
    op.create_table('subscriptions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('plan_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('starts_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('ends_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('payment_reference', sa.String(length=255), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['plan_id'], ['plans.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_subscriptions_tenant_id', 'subscriptions', ['tenant_id'], unique=False)
    op.create_table('support_tickets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('owner_id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=True),
    sa.Column('subject', sa.String(length=255), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('priority', sa.String(length=20), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['platform_owners.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_support_tickets_owner_status', 'support_tickets', ['owner_id', 'status'], unique=False)
    op.create_index('idx_support_tickets_tenant_id', 'support_tickets', ['tenant_id'], unique=False)
    op.create_table('tenant_modules',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('module_key', sa.String(length=50), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('enabled_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('enabled_by', sa.UUID(), nullable=True),
    sa.Column('disabled_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('disabled_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'module_key', name='uq_tenant_modules__tenant_id_module_key')
    )
    op.create_table('tenant_settings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'key', name='uq_tenant_settings__tenant_id_key')
    )
    op.create_table('classes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('department_id', sa.UUID(), nullable=False),
    sa.Column('academic_year_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('max_strength', sa.Integer(), nullable=False),
    sa.Column('class_teacher_id', sa.UUID(), nullable=True),
    sa.Column('room_no', sa.String(length=20), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['academic_year_id'], ['academic_years.id'], ),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'department_id', 'academic_year_id', 'code', name='uq_classes__tenant_id_dept_year_code')
    )
    op.create_index('idx_classes_tenant_id', 'classes', ['tenant_id'], unique=False)
    op.create_table('platform_invoice_lines',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('invoice_id', sa.UUID(), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('hsn_sac', sa.String(length=10), nullable=True),
    sa.Column('quantity', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('tax_rate', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('line_total', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['invoice_id'], ['platform_invoices.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('support_ticket_messages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('ticket_id', sa.UUID(), nullable=False),
    sa.Column('author_role', sa.String(length=20), nullable=False),
    sa.Column('author_id', sa.UUID(), nullable=True),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['ticket_id'], ['support_tickets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_support_ticket_messages_ticket_id', 'support_ticket_messages', ['ticket_id'], unique=False)
    op.create_table('student_enrollments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('class_id', sa.UUID(), nullable=False),
    sa.Column('academic_year_id', sa.UUID(), nullable=False),
    sa.Column('roll_number', sa.String(length=50), nullable=True),
    sa.Column('enrollment_date', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('transferred_to', sa.UUID(), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['academic_year_id'], ['academic_years.id'], ),
    sa.ForeignKeyConstraint(['class_id'], ['classes.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.ForeignKeyConstraint(['transferred_to'], ['classes.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('student_id', 'class_id', 'academic_year_id', name='uq_student_enrollments__student_id_class_id_academic_year_id')
    )
    op.create_index('idx_student_enrollments_class_id', 'student_enrollments', ['class_id'], unique=False)
    op.create_index('idx_student_enrollments_tenant_id', 'student_enrollments', ['tenant_id'], unique=False)
    op.create_table('subjects',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('class_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('code', sa.String(length=30), nullable=False),
    sa.Column('subject_type', sa.String(length=20), nullable=False),
    sa.Column('credits', sa.Integer(), nullable=True),
    sa.Column('max_marks', sa.Integer(), nullable=False),
    sa.Column('passing_marks', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['class_id'], ['classes.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'class_id', 'code', name='uq_subjects__tenant_id_class_id_code')
    )
    op.create_index('idx_subjects_tenant_id', 'subjects', ['tenant_id'], unique=False)
    op.create_table('teacher_subjects',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('teacher_id', sa.UUID(), nullable=False),
    sa.Column('subject_id', sa.UUID(), nullable=False),
    sa.Column('role_in_subject', sa.String(length=50), nullable=False),
    sa.Column('assigned_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('assigned_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['assigned_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ),
    sa.ForeignKeyConstraint(['teacher_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('teacher_id', 'subject_id', 'role_in_subject', name='uq_teacher_subjects__teacher_id_subject_id_role_in_subject')
    )
    op.create_index('idx_teacher_subjects_subject_id', 'teacher_subjects', ['subject_id'], unique=False)
    op.create_index('idx_teacher_subjects_tenant_id', 'teacher_subjects', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_teacher_subjects_tenant_id', table_name='teacher_subjects')
    op.drop_index('idx_teacher_subjects_subject_id', table_name='teacher_subjects')
    op.drop_table('teacher_subjects')
    op.drop_index('idx_subjects_tenant_id', table_name='subjects')
    op.drop_table('subjects')
    op.drop_index('idx_student_enrollments_tenant_id', table_name='student_enrollments')
    op.drop_index('idx_student_enrollments_class_id', table_name='student_enrollments')
    op.drop_table('student_enrollments')
    op.drop_index('idx_support_ticket_messages_ticket_id', table_name='support_ticket_messages')
    op.drop_table('support_ticket_messages')
    op.drop_table('platform_invoice_lines')
    op.drop_index('idx_classes_tenant_id', table_name='classes')
    op.drop_table('classes')
    op.drop_table('tenant_settings')
    op.drop_table('tenant_modules')
    op.drop_index('idx_support_tickets_tenant_id', table_name='support_tickets')
    op.drop_index('idx_support_tickets_owner_status', table_name='support_tickets')
    op.drop_table('support_tickets')
    op.drop_index('idx_subscriptions_tenant_id', table_name='subscriptions')
    op.drop_table('subscriptions')
    op.drop_index('uq_role_assignments__user_role_tenant_scope', table_name='role_assignments')
    op.drop_index('idx_ra_user_id', table_name='role_assignments')
    op.drop_index('idx_ra_tenant_role', table_name='role_assignments')
    op.drop_index('idx_ra_scope_id', table_name='role_assignments', postgresql_where='scope_id IS NOT NULL')
    op.drop_table('role_assignments')
    op.drop_index('idx_platform_payments_tenant_id', table_name='platform_payments')
    op.drop_table('platform_payments')
    op.drop_index('idx_platform_invoices_tenant_id', table_name='platform_invoices')
    op.drop_table('platform_invoices')
    op.drop_index('idx_departments_tenant_id', table_name='departments')
    op.drop_table('departments')
    op.drop_index('idx_academic_years_tenant_id', table_name='academic_years')
    op.drop_table('academic_years')
    op.drop_index('idx_user_sessions_user_id', table_name='user_sessions')
    op.drop_index('idx_user_sessions_expires_at', table_name='user_sessions')
    op.drop_table('user_sessions')
    op.drop_table('tenants')
    op.drop_index('idx_platform_sessions_user_id', table_name='platform_sessions')
    op.drop_index('idx_platform_sessions_expires_at', table_name='platform_sessions')
    op.drop_table('platform_sessions')
    op.drop_index('uq_permissions__role_id_module_key_action', table_name='permissions')
    op.drop_table('permissions')
    op.drop_index('idx_owner_sessions_owner_id', table_name='owner_sessions')
    op.drop_index('idx_owner_sessions_expires_at', table_name='owner_sessions')
    op.drop_table('owner_sessions')
    op.drop_index('uq_users__tenant_id_student_roll_no', table_name='users', postgresql_where='student_roll_no IS NOT NULL')
    op.drop_index('uq_users__tenant_id_email', table_name='users', postgresql_where='email IS NOT NULL')
    op.drop_index('idx_users_tenant_id', table_name='users')
    op.drop_index('idx_users_is_active', table_name='users')
    op.drop_index('idx_users_email', table_name='users', postgresql_where='email IS NOT NULL')
    op.drop_index('idx_users_deleted_at', table_name='users', postgresql_where='deleted_at IS NULL')
    op.drop_table('users')
    op.drop_index('idx_service_requests_work_email', table_name='service_requests')
    op.drop_index('idx_service_requests_status_created_at', table_name='service_requests')
    op.drop_table('service_requests')
    op.drop_table('roles')
    op.drop_table('platform_users')
    op.drop_index('idx_platform_owners_email', table_name='platform_owners')
    op.drop_table('platform_owners')
    op.drop_table('plans')
    op.drop_index('idx_outbox_emails_status', table_name='outbox_emails')
    op.drop_table('outbox_emails')
    op.drop_index('idx_orders_status_created_at', table_name='orders')
    op.drop_index('idx_orders_owner_platform_user_id', table_name='orders')
    op.drop_index('idx_orders_contact_email', table_name='orders')
    op.drop_table('orders')
    op.drop_table('modules')
    op.drop_table('coupons')
    # ### end Alembic commands ###
